// WARNING: File is autogenerated, changes are overwritten!
val_t *native_myadd (exec_t *exec, val_t *args);
val_t *native_getint (exec_t *exec, val_t *args);
val_t *native_random (exec_t *exec, val_t *args);
val_t *native_getstring (exec_t *exec, val_t *args);
val_t *native_print (exec_t *exec, val_t *args);
val_t *call_native (exec_t *exec, char *id, val_t *args) {
 if (0) {
  } else if (strcmp(id, "myadd") == 0) {
     return native_myadd(exec, args);
  } else if (strcmp(id, "getint") == 0) {
     return native_getint(exec, args);
  } else if (strcmp(id, "random") == 0) {
     return native_random(exec, args);
  } else if (strcmp(id, "getstring") == 0) {
     return native_getstring(exec, args);
  } else if (strcmp(id, "print") == 0) {
     return native_print(exec, args);
 } else { return NULL; }
}
